# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["aftahi334@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = "Settler AI Bot"
language = "rust"
manifest_version = 3
name = "settlers"
service_id = ""

[scripts]
  build = "cargo build --bin settlers --release --target wasm32-wasi --color always"
